package br.com.pizzaria.view;

import br.com.dao.FuncionarioDao;
import br.com.pizzaria.model.Funcionario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class jfCadastroFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form jfCadastroFuncionario
     */
    public jfCadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JT_Nome = new javax.swing.JTextField();
        JT_Cpf = new javax.swing.JTextField();
        JT_Salario = new javax.swing.JTextField();
        JT_Telefone = new javax.swing.JTextField();
        jlnome = new javax.swing.JLabel();
        jlcpf = new javax.swing.JLabel();
        jlsalario = new javax.swing.JLabel();
        jltelefone = new javax.swing.JLabel();
        JT_Bairro = new javax.swing.JTextField();
        jlbairro = new javax.swing.JLabel();
        JT_Numero = new javax.swing.JTextField();
        jlnumero = new javax.swing.JLabel();
        jlcomplemento = new javax.swing.JLabel();
        JT_Complemento = new javax.swing.JTextField();
        jlcargo = new javax.swing.JLabel();
        JT_Cargo = new javax.swing.JTextField();
        jlcomplemento1 = new javax.swing.JLabel();
        JT_Logradouro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JT_ID_FUNCIONARIO = new javax.swing.JTextField();
        jlid_funcionario = new javax.swing.JLabel();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbInserir = new javax.swing.JButton();
        jbConsultarId = new javax.swing.JButton();
        JT_sexo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 209, 227));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Funcionário");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de Funcionario");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setAutoscrolls(true);
        jPanel1.setName(""); // NOI18N

        jlnome.setText("Nome:");

        jlcpf.setText("CPF:");

        jlsalario.setText("Salário:");

        jltelefone.setText("Telefone:");

        JT_Bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_BairroActionPerformed(evt);
            }
        });

        jlbairro.setText("Bairro:");

        JT_Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_NumeroActionPerformed(evt);
            }
        });

        jlnumero.setText("Número:");

        jlcomplemento.setText("Complemento:");

        jlcargo.setText("Cargo:");

        jlcomplemento1.setText("Logradouro");

        jLabel6.setText("Sexo:");

        jlid_funcionario.setText("ID Funcionário:");

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbInserir.setText("Inserir");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jbConsultarId.setText("Consultar");
        jbConsultarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JT_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlbairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JT_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlcargo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JT_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlcomplemento1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(JT_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jlnumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JT_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jlcomplemento)
                                .addGap(14, 14, 14)
                                .addComponent(JT_Complemento))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlid_funcionario)
                                            .addComponent(jlnome)
                                            .addComponent(jlcpf)
                                            .addComponent(jlsalario))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jltelefone)
                                        .addGap(37, 37, 37)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JT_Telefone, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                    .addComponent(JT_Salario)
                                    .addComponent(JT_Cpf)
                                    .addComponent(JT_Nome)
                                    .addComponent(JT_ID_FUNCIONARIO))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(48, Short.MAX_VALUE)
                        .addComponent(jbConsultarId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbInserir)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_ID_FUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlid_funcionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlnome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlcpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JT_Salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlsalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jltelefone)
                    .addComponent(JT_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JT_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlnumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlcomplemento)
                    .addComponent(JT_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlcomplemento1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlcargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JT_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterar)
                    .addComponent(jbExcluir)
                    .addComponent(jbInserir)
                    .addComponent(jbConsultarId))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConsultarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarIdActionPerformed
        // TODO add your handling code here:
        Funcionario Fun = new Funcionario();
        FuncionarioDao funDao = new FuncionarioDao();
        Fun.setIdFuncionario(Integer.parseInt(JT_ID_FUNCIONARIO.getText()));

        this.JT_Nome.setText(Fun.getNomeFuncionario());
        this.JT_Cargo.setText(Fun.getIdCargo());
        this.JT_Complemento.setText(Fun.getComplemento());
        this.JT_Cpf.setText(Fun.getCpf());
        this.JT_Logradouro.setText(Fun.getLogradouro());
        this.JT_Numero.setText(Fun.getNumero());
        this.JT_Salario.setText(Float.toString(Fun.getSalario()));
        this.JT_Telefone.setText(Fun.getTelefone());

        try {
            funDao.ConsultarFuncionario(Fun);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbConsultarIdActionPerformed

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        // TODO add your handling code here:
        Funcionario Fun = new Funcionario();
        FuncionarioDao Fundao = new FuncionarioDao();

        Fun.setNomeFuncionario(JT_Nome.getText());
        Fun.setCpf(JT_Cpf.getText());
        Fun.setSalario(Float.parseFloat(JT_Salario.getText()));
        Fun.setTelefone(JT_Telefone.getText());
        Fun.setBairro(JT_Bairro.getText());
        Fun.setNumero(JT_Numero.getText());
        Fun.setLogradouro(JT_Logradouro.getText());
        Fun.setComplemento(JT_Complemento.getText());
        Fun.setIdCargo(JT_Cargo.getText());
        Fun.setSexo(JT_sexo.getText());

        try {
            Fundao.Inserir(Fun);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbInserirActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:

        Funcionario Fun = new Funcionario();
        FuncionarioDao Fundao = new FuncionarioDao();
        Fun.setIdFuncionario(Integer.parseInt(JT_ID_FUNCIONARIO.getText()));

        try {
            Fundao.remove(Fun);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        Funcionario Fun = new Funcionario();
        FuncionarioDao Fundao = new FuncionarioDao();

        Fun.setIdFuncionario(Integer.parseInt(JT_ID_FUNCIONARIO.getText()));

        Fun.setNomeFuncionario(JT_Nome.getText());
        Fun.setCpf(JT_Cpf.getText());
        Fun.setSalario(Float.parseFloat(JT_Salario.getText()));
        Fun.setTelefone(JT_Telefone.getText());
        Fun.setBairro(JT_Bairro.getText());
        Fun.setNumero(JT_Numero.getText());
        Fun.setLogradouro(JT_Logradouro.getText());
        Fun.setComplemento(JT_Complemento.getText());
        Fun.setIdCargo(JT_Cargo.getText());

        Fundao.Altera(Fun);
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void JT_NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_NumeroActionPerformed

    private void JT_BairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_BairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_BairroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JT_Bairro;
    private javax.swing.JTextField JT_Cargo;
    private javax.swing.JTextField JT_Complemento;
    private javax.swing.JTextField JT_Cpf;
    private javax.swing.JTextField JT_ID_FUNCIONARIO;
    private javax.swing.JTextField JT_Logradouro;
    private javax.swing.JTextField JT_Nome;
    private javax.swing.JTextField JT_Numero;
    private javax.swing.JTextField JT_Salario;
    private javax.swing.JTextField JT_Telefone;
    private javax.swing.JTextField JT_sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbConsultarId;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbInserir;
    private javax.swing.JLabel jlbairro;
    private javax.swing.JLabel jlcargo;
    private javax.swing.JLabel jlcomplemento;
    private javax.swing.JLabel jlcomplemento1;
    private javax.swing.JLabel jlcpf;
    private javax.swing.JLabel jlid_funcionario;
    private javax.swing.JLabel jlnome;
    private javax.swing.JLabel jlnumero;
    private javax.swing.JLabel jlsalario;
    private javax.swing.JLabel jltelefone;
    // End of variables declaration//GEN-END:variables
}
