package br.com.pizzaria.view;

import br.com.dao.FornecedorDao;
import br.com.pizzaria.model.Fornecedor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class jfCadastroFornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form jfCadastroFornecedor
     */
    public jfCadastroFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JT_Telefone = new javax.swing.JTextField();
        jbInserir = new javax.swing.JButton();
        jlbairro = new javax.swing.JLabel();
        JT_Bairro = new javax.swing.JTextField();
        jlLogradouro = new javax.swing.JLabel();
        JT_Logradouro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jlnumero = new javax.swing.JLabel();
        jlnome = new javax.swing.JLabel();
        JT_Numero = new javax.swing.JTextField();
        JT_Nome = new javax.swing.JTextField();
        jlcomplemento = new javax.swing.JLabel();
        jlcnpj = new javax.swing.JLabel();
        JT_Complemento = new javax.swing.JTextField();
        JT_Cnpj = new javax.swing.JTextField();
        jbExcluir = new javax.swing.JButton();
        jltelefone = new javax.swing.JLabel();
        jbAlterar = new javax.swing.JButton();
        jlid_fornecedor = new javax.swing.JLabel();
        JT_ID_FORNECEDOR = new javax.swing.JTextField();
        jbConsultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlfuncionaRIO_id_funcionario = new javax.swing.JLabel();
        JT_FUNCIONARIO_ID_FUNCIONARIO = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro Fornecedor");

        JT_Telefone.setToolTipText("");

        jbInserir.setText("Inserir");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jlbairro.setText("Bairro:");

        jlLogradouro.setText("Logradouro:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de Fornecedor");

        jlnumero.setText("Numero:");

        jlnome.setText("Nome:");

        jlcomplemento.setText("Complemento:");

        jlcnpj.setText("CNPJ:");

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jltelefone.setText("Telefone:");

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jlid_fornecedor.setText("ID Fornecedor:");

        jbConsultar.setText("Consultar");
        jbConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarActionPerformed(evt);
            }
        });

        jlfuncionaRIO_id_funcionario.setText("Funcionario ID Funcionario: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jbAlterar)
                                .addGap(47, 47, 47)
                                .addComponent(jbConsultar)
                                .addGap(42, 42, 42)
                                .addComponent(jbExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlfuncionaRIO_id_funcionario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JT_FUNCIONARIO_ID_FUNCIONARIO))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlid_fornecedor)
                                            .addComponent(jLabel2)
                                            .addComponent(jlcnpj)
                                            .addComponent(jltelefone)
                                            .addComponent(jlbairro)
                                            .addComponent(jlLogradouro)
                                            .addComponent(jlnumero)
                                            .addComponent(jlcomplemento)
                                            .addComponent(jlnome))
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JT_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JT_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JT_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JT_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JT_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JT_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JT_ID_FORNECEDOR, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JT_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(10, 10, 10)
                        .addComponent(jbInserir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlfuncionaRIO_id_funcionario)
                    .addComponent(JT_FUNCIONARIO_ID_FUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlid_fornecedor))
                    .addComponent(JT_ID_FORNECEDOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlnome)
                    .addComponent(JT_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlcnpj)
                    .addComponent(JT_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jltelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbairro)
                    .addComponent(JT_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLogradouro)
                    .addComponent(JT_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlnumero)
                    .addComponent(JT_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlcomplemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterar)
                    .addComponent(jbExcluir)
                    .addComponent(jbInserir)
                    .addComponent(jbConsultar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        Fornecedor For = new Fornecedor();
        FornecedorDao Fordao = new FornecedorDao();
        For.setIdFornecedor(Integer.parseInt(JT_ID_FORNECEDOR.getText()));
        For.setNomeFornecedor(JT_Nome.getText());
        For.setCnpj(JT_Cnpj.getText());
        For.setTelefone(JT_Telefone.getText());
        For.setBairro(JT_Bairro.getText());
        For.setNumero(JT_Numero.getText());
        For.setLogradouro(JT_Logradouro.getText());
        For.setComplemento(JT_Complemento.getText());

        Fordao.Altera(For);
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:
        Fornecedor For = new Fornecedor();
        FornecedorDao Fordao = new FornecedorDao();
        For.setIdFornecedor(Integer.parseInt(JT_ID_FORNECEDOR.getText()));

        try {
            Fordao.remove(For);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        // TODO add your handling code here:
        Fornecedor For = new Fornecedor();
        FornecedorDao Fordao = new FornecedorDao();

        For.getFun().setIdFuncionario(Integer.parseInt(JT_FUNCIONARIO_ID_FUNCIONARIO.getText()));

        For.setNomeFornecedor(JT_Nome.getText());
        For.setCnpj(JT_Cnpj.getText());
        For.setTelefone(JT_Telefone.getText());
        For.setBairro(JT_Bairro.getText());
        For.setNumero(JT_Numero.getText());
        For.setLogradouro(JT_Logradouro.getText());
        For.setComplemento(JT_Complemento.getText());

        try {
            Fordao.Inserir(For);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbInserirActionPerformed

    private void jbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarActionPerformed
        // TODO add your handling code here:
        Fornecedor For = new Fornecedor();
        FornecedorDao Fordao = new FornecedorDao();
        For.setIdFornecedor(Integer.parseInt(JT_ID_FORNECEDOR.getText()));
        this.JT_Nome.setText(For.getNomeFornecedor());
        this.JT_Bairro.setText(For.getBairro());
        this.JT_Cnpj.setText(For.getCnpj());
        this.JT_Complemento.setText(For.getComplemento());
        this.JT_Logradouro.setText(For.getLogradouro());
        this.JT_Numero.setText(For.getNumero());
        this.JT_Telefone.setText(For.getTelefone());

        try {
            Fordao.ConsultarId(For);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroFornecedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JT_Bairro;
    private javax.swing.JTextField JT_Cnpj;
    private javax.swing.JTextField JT_Complemento;
    private javax.swing.JTextField JT_FUNCIONARIO_ID_FUNCIONARIO;
    private javax.swing.JTextField JT_ID_FORNECEDOR;
    private javax.swing.JTextField JT_Logradouro;
    private javax.swing.JTextField JT_Nome;
    private javax.swing.JTextField JT_Numero;
    private javax.swing.JTextField JT_Telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbInserir;
    private javax.swing.JLabel jlLogradouro;
    private javax.swing.JLabel jlbairro;
    private javax.swing.JLabel jlcnpj;
    private javax.swing.JLabel jlcomplemento;
    private javax.swing.JLabel jlfuncionaRIO_id_funcionario;
    private javax.swing.JLabel jlid_fornecedor;
    private javax.swing.JLabel jlnome;
    private javax.swing.JLabel jlnumero;
    private javax.swing.JLabel jltelefone;
    // End of variables declaration//GEN-END:variables
}
