/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pizzaria.view;

import br.com.dao.PizzaHasVendaDao;
import br.com.dao.VendaDao;
import br.com.pizzaria.model.PizzaHasVenda;
import br.com.pizzaria.model.Venda;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Fábia Piovesan
 */
public class jfCadastroVenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form jfCadastroVenda
     */
    public jfCadastroVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbConfirmar = new javax.swing.JButton();
        jldatadavenda = new javax.swing.JLabel();
        JT_DataDaVenda = new javax.swing.JTextField();
        jlvalor = new javax.swing.JLabel();
        JT_Valor = new javax.swing.JTextField();
        jlnumerodamesa = new javax.swing.JLabel();
        JT_NumeroDaMesa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbCOnsultar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JT_CLIENTE_ID_CLIENTE = new javax.swing.JTextField();
        jlcliente_id_cliente = new javax.swing.JLabel();
        jlfuncionario_id_funcionario = new javax.swing.JLabel();
        JT_FUNCIONARIO_ID_FUNCIONARIO = new javax.swing.JTextField();
        jbExcluir = new javax.swing.JButton();
        JT_IdPizza = new javax.swing.JTextField();
        jlcliente_id_cliente1 = new javax.swing.JLabel();
        jlcliente_id_cliente2 = new javax.swing.JLabel();
        JT_Quantidade = new javax.swing.JTextField();
        jlfuncionario_id_funcionario1 = new javax.swing.JLabel();
        JT_IdVenda = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Venda");

        jbConfirmar.setText("Inserir");
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        jldatadavenda.setText("Data da Venda:");

        jlvalor.setText("Valor:");

        jlnumerodamesa.setText("Número da Mesa:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Venda");

        jbCOnsultar.setText("Consultar");
        jbCOnsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCOnsultarActionPerformed(evt);
            }
        });

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jlcliente_id_cliente.setText("Cliente ID Cliente:");

        jlfuncionario_id_funcionario.setText("Funcionario ID Funcionário:");

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jlcliente_id_cliente1.setText("Id Pizza");

        jlcliente_id_cliente2.setText("Quantidade");

        jlfuncionario_id_funcionario1.setText("Id Venda:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jbAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCOnsultar)
                        .addGap(18, 18, 18)
                        .addComponent(jbExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jbConfirmar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jldatadavenda)
                            .addComponent(jlvalor)
                            .addComponent(jlnumerodamesa)
                            .addComponent(jLabel2)
                            .addComponent(jlfuncionario_id_funcionario)
                            .addComponent(jlcliente_id_cliente)
                            .addComponent(jlcliente_id_cliente1)
                            .addComponent(jlcliente_id_cliente2)
                            .addComponent(jlfuncionario_id_funcionario1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT_CLIENTE_ID_CLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_FUNCIONARIO_ID_FUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_DataDaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_NumeroDaMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_IdPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JT_IdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlfuncionario_id_funcionario1)
                    .addComponent(JT_IdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlfuncionario_id_funcionario)
                    .addComponent(JT_FUNCIONARIO_ID_FUNCIONARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jlcliente_id_cliente))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                                .addComponent(JT_CLIENTE_ID_CLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JT_IdPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlcliente_id_cliente1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlcliente_id_cliente2)
                    .addComponent(JT_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jldatadavenda)
                    .addComponent(JT_DataDaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlvalor)
                    .addComponent(JT_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_NumeroDaMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlnumerodamesa))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCOnsultar)
                    .addComponent(jbConfirmar)
                    .addComponent(jbAlterar)
                    .addComponent(jbExcluir))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        // TODO add your handling code here:

        PizzaHasVenda phv = new PizzaHasVenda();
        PizzaHasVendaDao phvDao = new PizzaHasVendaDao();

        Venda venda = new Venda();
        VendaDao vendaDao = new VendaDao();

        venda.getCli().setId(Integer.parseInt(JT_CLIENTE_ID_CLIENTE.getText()));
        venda.setDataVenda(Date.valueOf(JT_DataDaVenda.getText()));
        venda.getFun().setIdFuncionario(Integer.parseInt(JT_FUNCIONARIO_ID_FUNCIONARIO.getText()));
        venda.getMes().setIdMesa(Integer.parseInt(JT_IdPizza.getText()));
        venda.setValor(Float.parseFloat(JT_Valor.getText()));

        try {
            vendaDao.Inserir(venda);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroVenda.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbConfirmarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:
        Venda venda = new Venda();
        VendaDao vendaDao = new VendaDao();

        venda.setIdVenda(Integer.parseInt(JT_IdPizza.getText()));

        try {
            vendaDao.remove(venda);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroVenda.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        Venda venda = new Venda();
        VendaDao vendaDao = new VendaDao();

        venda.setIdVenda(Integer.parseInt(JT_IdPizza.getText()));
        venda.getCli().setId(Integer.parseInt(JT_CLIENTE_ID_CLIENTE.getText()));
        venda.setDataVenda(Date.valueOf(JT_DataDaVenda.getText()));
        venda.getFun().setIdFuncionario(Integer.parseInt(JT_FUNCIONARIO_ID_FUNCIONARIO.getText()));
        venda.getMes().setIdMesa(Integer.parseInt(JT_IdPizza.getText()));
        venda.setValor(Float.parseFloat(JT_Valor.getText()));

        try {
            vendaDao.altera(venda);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroVenda.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbCOnsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCOnsultarActionPerformed
        // TODO add your handling code here:
        Venda venda = new Venda();
        VendaDao vendaDao = new VendaDao();

        venda.setIdVenda(Integer.parseInt(JT_IdPizza.getText()));

        this.JT_DataDaVenda.setText(String.valueOf(venda.getDataVenda()));
        this.JT_CLIENTE_ID_CLIENTE.setText(String.valueOf(venda.getDataVenda()));
        this.JT_FUNCIONARIO_ID_FUNCIONARIO.setText(String.valueOf(venda.getFun().getIdFuncionario()));
        this.JT_NumeroDaMesa.setText(String.valueOf(venda.getMes().getIdMesa()));
        this.JT_Valor.setText(String.valueOf(venda.getValor()));

        try {
            vendaDao.ConsultarId(venda);

        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroVenda.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbCOnsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JT_CLIENTE_ID_CLIENTE;
    private javax.swing.JTextField JT_DataDaVenda;
    private javax.swing.JTextField JT_FUNCIONARIO_ID_FUNCIONARIO;
    private javax.swing.JTextField JT_IdPizza;
    private javax.swing.JTextField JT_IdVenda;
    private javax.swing.JTextField JT_NumeroDaMesa;
    private javax.swing.JTextField JT_Quantidade;
    private javax.swing.JTextField JT_Valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCOnsultar;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JLabel jlcliente_id_cliente;
    private javax.swing.JLabel jlcliente_id_cliente1;
    private javax.swing.JLabel jlcliente_id_cliente2;
    private javax.swing.JLabel jldatadavenda;
    private javax.swing.JLabel jlfuncionario_id_funcionario;
    private javax.swing.JLabel jlfuncionario_id_funcionario1;
    private javax.swing.JLabel jlnumerodamesa;
    private javax.swing.JLabel jlvalor;
    // End of variables declaration//GEN-END:variables
}
