/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pizzaria.view;

import br.com.dao.SaborDao;
import br.com.pizzaria.model.Sabor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Fábia Piovesan
 */
public class jfCadastroSabor extends javax.swing.JInternalFrame {

    /**
     * Creates new form jfCadastroSabor
     */
    public jfCadastroSabor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlnome = new javax.swing.JLabel();
        JT_Nome = new javax.swing.JTextField();
        jlnomefuncionario = new javax.swing.JLabel();
        JT_NomeFuncionario = new javax.swing.JTextField();
        jbExcluir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbInserir = new javax.swing.JButton();
        jlid_sabor = new javax.swing.JLabel();
        JT_ID_SABOR = new javax.swing.JTextField();
        jbConsultar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Sabor");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de Sabor");

        jlnome.setText("Nome:");

        jlnomefuncionario.setText("Nome Funcionario:");

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbInserir.setText("Inserir");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jlid_sabor.setText("ID Sabor:");

        jbConsultar.setText("Consultar");
        jbConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlnome)
                    .addComponent(jlnomefuncionario)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbConsultar))
                    .addComponent(jlid_sabor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JT_Nome, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(JT_NomeFuncionario)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jbExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jbInserir))
                    .addComponent(JT_ID_SABOR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlid_sabor)
                    .addComponent(JT_ID_SABOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlnome)
                    .addComponent(JT_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlnomefuncionario)
                    .addComponent(JT_NomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbExcluir)
                    .addComponent(jbInserir)
                    .addComponent(jbAlterar)
                    .addComponent(jbConsultar))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        // TODO add your handling code here:
        Sabor sabor = new Sabor();
        SaborDao saboDao = new SaborDao();
        
        sabor.setNomeSabor(JT_Nome.getText());
        sabor.getFun().setIdFuncionario(Integer.parseInt(JT_NomeFuncionario.getText()));
        
        try {
            saboDao.Inserir(sabor);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroSabor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbInserirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        Sabor sabor = new Sabor();
        SaborDao saboDao = new SaborDao();
        
        sabor.setIdSabor(Integer.parseInt(JT_ID_SABOR.getText()));
        sabor.setNomeSabor(JT_Nome.getText());
        sabor.getFun().setIdFuncionario(Integer.parseInt(JT_NomeFuncionario.getText()));
        
        try {
            saboDao.altera(sabor);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroSabor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:
        Sabor sabor = new Sabor();
        SaborDao saboDao = new SaborDao();
        
        sabor.setIdSabor(Integer.parseInt(JT_ID_SABOR.getText()));

        try {
            saboDao.remove(sabor);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroSabor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarActionPerformed
        // TODO add your handling code here:
        Sabor sabor = new Sabor();
        SaborDao saboDao = new SaborDao();
        
        sabor.setIdSabor(Integer.parseInt(JT_ID_SABOR.getText()));
        
        this.JT_Nome.setText(sabor.getNomeSabor());
        this.JT_NomeFuncionario.setText(String.valueOf(sabor.getFun().getIdFuncionario()));
        
        try {
            saboDao.ConsultarSabor(sabor);
                    
                    } catch (SQLException ex) {
            Logger.getLogger(jfCadastroSabor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JT_ID_SABOR;
    private javax.swing.JTextField JT_Nome;
    private javax.swing.JTextField JT_NomeFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbInserir;
    private javax.swing.JLabel jlid_sabor;
    private javax.swing.JLabel jlnome;
    private javax.swing.JLabel jlnomefuncionario;
    // End of variables declaration//GEN-END:variables
}
