/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pizzaria.view;

import br.com.dao.ProdutoDao;
import br.com.pizzaria.model.Produto;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Fábia Piovesan
 */
public class jfCadastroProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form jfCadastroProduto
     */
    public jfCadastroProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbExcluir = new javax.swing.JButton();
        jlquantidade = new javax.swing.JLabel();
        jbAlterar = new javax.swing.JButton();
        JT_Quantidade = new javax.swing.JTextField();
        jbInserir = new javax.swing.JButton();
        jlvalor = new javax.swing.JLabel();
        JT_Valor = new javax.swing.JTextField();
        jlvalordeentrada = new javax.swing.JLabel();
        JT_DataDeEntrada = new javax.swing.JTextField();
        jldatavencimento = new javax.swing.JLabel();
        JT_DataVencimento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jlnome = new javax.swing.JLabel();
        JT_Nome = new javax.swing.JTextField();
        jlid_produto = new javax.swing.JLabel();
        JT_ID_PRODUTO = new javax.swing.JTextField();
        jlid_produto1 = new javax.swing.JLabel();
        JT_Fornecedor = new javax.swing.JTextField();
        jlid_produto2 = new javax.swing.JLabel();
        JT_Funcionario = new javax.swing.JTextField();
        jbConsultar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Produto");

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jlquantidade.setText("Quantidade:");

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbInserir.setText("Inserir");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jlvalor.setText("Valor:");

        jlvalordeentrada.setText("Data de Entrada:");

        jldatavencimento.setText("Data Vencimento:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de Produto");

        jlnome.setText("Nome:");

        jlid_produto.setText("ID Produto:");

        jlid_produto1.setText("Fornecedor");

        JT_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_FornecedorActionPerformed(evt);
            }
        });

        jlid_produto2.setText("Funcionario");

        jbConsultar.setText("Consultar");
        jbConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlvalordeentrada)
                            .addComponent(jlquantidade)
                            .addComponent(jlnome)
                            .addComponent(jlvalor)
                            .addComponent(jldatavencimento)
                            .addComponent(jlid_produto)
                            .addComponent(jlid_produto1)
                            .addComponent(jlid_produto2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jbAlterar)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jbInserir)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JT_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(JT_Fornecedor)
                            .addComponent(jLabel1)
                            .addComponent(JT_DataDeEntrada)
                            .addComponent(JT_Valor)
                            .addComponent(JT_Quantidade)
                            .addComponent(JT_Nome)
                            .addComponent(JT_DataVencimento)
                            .addComponent(JT_ID_PRODUTO))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlid_produto)
                    .addComponent(JT_ID_PRODUTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlnome)
                    .addComponent(JT_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlquantidade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlvalor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_DataDeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlvalordeentrada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_DataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jldatavencimento))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlid_produto1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlid_produto2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbExcluir)
                    .addComponent(jbInserir)
                    .addComponent(jbAlterar)
                    .addComponent(jbConsultar))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        // TODO add your handling code here:
        Produto produto = new Produto();
        ProdutoDao produtoDao = new ProdutoDao();

        produto.setQuantidade(Integer.parseInt(JT_Quantidade.getText()));
        produto.setValor(Float.parseFloat(JT_Valor.getText()));
        produto.getFun().setIdFuncionario(Integer.parseInt(JT_Funcionario.getText()));
        produto.getForn().setIdFornecedor(Integer.parseInt(JT_Fornecedor.getText()));
        produto.setNomeProduto(JT_Fornecedor.getText());
        produto.setDataEntrada(Date.valueOf(JT_DataDeEntrada.getText()));
        produto.setDataVencimento(Date.valueOf(JT_DataVencimento.getText()));

        try {
            produtoDao.Inserir(produto);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jbInserirActionPerformed

    private void JT_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_FornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_FornecedorActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:
        Produto produto = new Produto();
        ProdutoDao produtoDao = new ProdutoDao();

        produto.setIdProduto(Integer.parseInt(JT_ID_PRODUTO.getText()));

        try {
            produtoDao.remove(produto);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        Produto produto = new Produto();
        ProdutoDao produtoDao = new ProdutoDao();

        produto.setIdProduto(Integer.parseInt(JT_ID_PRODUTO.getText()));

        produto.setQuantidade(Integer.parseInt(JT_Quantidade.getText()));
        produto.setValor(Float.parseFloat(JT_Valor.getText()));
        produto.getFun().setIdFuncionario(Integer.parseInt(JT_Funcionario.getText()));
        produto.getForn().setIdFornecedor(Integer.parseInt(JT_Fornecedor.getText()));
        produto.setNomeProduto(JT_Fornecedor.getText());
        produto.setDataEntrada(Date.valueOf(JT_DataDeEntrada.getText()));
        produto.setDataVencimento(Date.valueOf(JT_DataVencimento.getText()));

        try {
            produtoDao.Altera(produto);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarActionPerformed
        // TODO add your handling code here:
        
        Produto produto = new Produto();
        ProdutoDao produtoDao = new ProdutoDao();
        
        produto.setIdProduto(Integer.parseInt(JT_ID_PRODUTO.getText()));
        
        this.JT_Nome.setText(produto.getNomeProduto());
        this.JT_Quantidade.setText(String.valueOf(produto.getQuantidade()));
        this.JT_Valor.setText(String.valueOf(produto.getValor()));
        this.JT_Fornecedor.setText(String.valueOf(produto.getForn().getIdFornecedor()));
        this.JT_Funcionario.setText(String.valueOf(produto.getFun().getIdFuncionario()));
        this.JT_DataDeEntrada.setText(String.valueOf(produto.getDataEntrada()));
        this.JT_DataVencimento.setText(String.valueOf(produto.getDataVencimento()));
        
        try {
            produtoDao.ConsultarProduto(produto);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JT_DataDeEntrada;
    private javax.swing.JTextField JT_DataVencimento;
    private javax.swing.JTextField JT_Fornecedor;
    private javax.swing.JTextField JT_Funcionario;
    private javax.swing.JTextField JT_ID_PRODUTO;
    private javax.swing.JTextField JT_Nome;
    private javax.swing.JTextField JT_Quantidade;
    private javax.swing.JTextField JT_Valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbInserir;
    private javax.swing.JLabel jldatavencimento;
    private javax.swing.JLabel jlid_produto;
    private javax.swing.JLabel jlid_produto1;
    private javax.swing.JLabel jlid_produto2;
    private javax.swing.JLabel jlnome;
    private javax.swing.JLabel jlquantidade;
    private javax.swing.JLabel jlvalor;
    private javax.swing.JLabel jlvalordeentrada;
    // End of variables declaration//GEN-END:variables
}
