package br.com.pizzaria.view;

import br.com.dao.ClienteDao;
import br.com.pizzaria.model.Cliente;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class jfCadastroCliente extends javax.swing.JInternalFrame {
    //    br.com.pizzaria.modeljfCadastroCliente mod = new br.com.pizzaria.modeljfCadastroCliente ();

    /**
     * Creates new form jfCadastroCliente
     */
    public jfCadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JT_Numero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jlLogradouro = new javax.swing.JLabel();
        JT_Nome = new javax.swing.JTextField();
        JT_Logradouro = new javax.swing.JTextField();
        jlnome = new javax.swing.JLabel();
        jlcomplemento = new javax.swing.JLabel();
        jlcpf = new javax.swing.JLabel();
        JT_Complemento = new javax.swing.JTextField();
        JT_Cpf = new javax.swing.JTextField();
        jbInserir = new javax.swing.JButton();
        jltelefone = new javax.swing.JLabel();
        jbAlterar = new javax.swing.JButton();
        JT_Telefone = new javax.swing.JTextField();
        jbExcluir = new javax.swing.JButton();
        jlbairro = new javax.swing.JLabel();
        JT_Bairro = new javax.swing.JTextField();
        jlnumero = new javax.swing.JLabel();
        jlid_cliente = new javax.swing.JLabel();
        JT_ID_CLIENTE = new javax.swing.JTextField();
        jbConsultar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro Cliente");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de Cliente");

        jlLogradouro.setText("Logradouro:");

        JT_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_NomeActionPerformed(evt);
            }
        });

        jlnome.setText("Nome:");

        jlcomplemento.setText("Complemento:");

        jlcpf.setText("CPF:");

        jbInserir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbInserir.setText("Inserir");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jltelefone.setText("Telefone:");

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jlbairro.setText("Bairro:");

        JT_Bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_BairroActionPerformed(evt);
            }
        });

        jlnumero.setText("Número:");

        jlid_cliente.setText("Id Cliente:");

        jbConsultar.setText("Consultar");
        jbConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jbAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlnome)
                            .addComponent(jlcpf)
                            .addComponent(jlbairro)
                            .addComponent(jlnumero)
                            .addComponent(jlLogradouro)
                            .addComponent(jltelefone)
                            .addComponent(jlcomplemento)
                            .addComponent(jlid_cliente))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JT_Nome)
                            .addComponent(JT_Cpf)
                            .addComponent(JT_Telefone)
                            .addComponent(JT_Bairro)
                            .addComponent(JT_Numero)
                            .addComponent(JT_Logradouro)
                            .addComponent(JT_Complemento)
                            .addComponent(JT_ID_CLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlid_cliente)
                            .addComponent(JT_ID_CLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JT_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlnome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlcpf)
                            .addComponent(JT_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jltelefone)
                            .addComponent(JT_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbairro)
                            .addComponent(JT_Bairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JT_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlnumero))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlLogradouro)
                            .addComponent(JT_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlcomplemento)
                            .addComponent(JT_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterar)
                    .addComponent(jbConsultar)
                    .addComponent(jbExcluir)
                    .addComponent(jbInserir))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JT_BairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_BairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_BairroActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:
        Cliente cli = new Cliente();
        ClienteDao clidao = new ClienteDao();
        cli.setNome(JT_Nome.getText());
        cli.setCpf(JT_Cpf.getText());
        cli.setTelefone(JT_Telefone.getText());
        cli.setBairro(JT_Bairro.getText());
        cli.setNumero(JT_Numero.getText());
        cli.setLogradouro(JT_Logradouro.getText());
        cli.setComplemento(JT_Complemento.getText());

        try {
            clidao.remove(cli);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbExcluirActionPerformed

    private void JT_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_NomeActionPerformed
        // TODO
    }//GEN-LAST:event_JT_NomeActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        Cliente cli = new Cliente();
        ClienteDao clidao = new ClienteDao();
        cli.setId(Integer.parseInt(JT_ID_CLIENTE.getText()));
        cli.setNome(JT_Nome.getText());
        cli.setCpf(JT_Cpf.getText());
        cli.setTelefone(JT_Telefone.getText());
        cli.setBairro(JT_Bairro.getText());
        cli.setNumero(JT_Numero.getText());
        cli.setLogradouro(JT_Logradouro.getText());
        cli.setComplemento(JT_Complemento.getText());

        clidao.altera(cli);

    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        //INSERIR
        Cliente cli = new Cliente();
        ClienteDao clidao = new ClienteDao();
        cli.setNome(JT_Nome.getText());
        cli.setCpf(JT_Cpf.getText());
        cli.setTelefone(JT_Telefone.getText());
        cli.setBairro(JT_Bairro.getText());
        cli.setNumero(JT_Numero.getText());
        cli.setLogradouro(JT_Logradouro.getText());
        cli.setComplemento(JT_Complemento.getText());

        try {
            clidao.Inserir(cli);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbInserirActionPerformed

    private void jbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarActionPerformed
        Cliente cli = new Cliente();
        ClienteDao clidao = new ClienteDao();
        cli.setId(Integer.parseInt(JT_ID_CLIENTE.getText()));
        this.JT_Nome.setText(cli.getNome());
        this.JT_Cpf.setText(cli.getCpf());
        this.JT_Telefone.setText(cli.getTelefone());
        this.JT_Bairro.setText(cli.getBairro());
        this.JT_Numero.setText(cli.getNumero());
        this.JT_Logradouro.setText(cli.getLogradouro());
        this.JT_Complemento.setText(cli.getComplemento());

        try {
            clidao.ConsultarId(cli);
        } catch (SQLException ex) {
            Logger.getLogger(jfCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JT_Bairro;
    private javax.swing.JTextField JT_Complemento;
    private javax.swing.JTextField JT_Cpf;
    private javax.swing.JTextField JT_ID_CLIENTE;
    private javax.swing.JTextField JT_Logradouro;
    private javax.swing.JTextField JT_Nome;
    private javax.swing.JTextField JT_Numero;
    private javax.swing.JTextField JT_Telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbInserir;
    private javax.swing.JLabel jlLogradouro;
    private javax.swing.JLabel jlbairro;
    private javax.swing.JLabel jlcomplemento;
    private javax.swing.JLabel jlcpf;
    private javax.swing.JLabel jlid_cliente;
    private javax.swing.JLabel jlnome;
    private javax.swing.JLabel jlnumero;
    private javax.swing.JLabel jltelefone;
    // End of variables declaration//GEN-END:variables
}
